### ISSUE TITLE
Add general `cmd` and `args` for tools object

### ISSUE THREAD

**Issue by colonesej** [ecmwf/pyflow-wellies#44]
### Is your feature request related to a problem? Please describe.

There are a few requests to customise the command and the arguments for some tools and data types, like mars and `copy`.

### Describe the solution you'd like

 I think we can generalise it and provide a common interface for any data and tool config entry

```yaml
data:
  type: mars
  cmd: /path/to/non/standard/mars_client

tools:
  packages:
    mypackage:
      type: git
      args: ["--origin github"] 

```
